### ISSUE TITLE
Run Algorithm

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/s1-example#2]
- [x] Try running the algorithm.

**Comment by wildintellect** [comment]
Job Queued 12d31b29-acfb-4bf8-a3b1-1d793410df46

**Comment by wildintellect** [comment]
```
Traceback (most recent call last):
  File "/app/s1-example/asf-s1-edc.py", line 65, in <module>
    download_test(output)
  File "/app/s1-example/asf-s1-edc.py", line 49, in download_test
    s3 = get_s3_client(asf_s3)
  File "/app/s1-example/asf-s1-edc.py", line 14, in get_s3_client
    creds=get_s3_creds(s3_cred_endpoint)
  File "/app/s1-example/asf-s1-edc.py", line 10, in get_s3_creds
    return maap.aws.earthdata_s3_credentials(url)
  File "/maap-py/maap/AWS.py", line 62, in earthdata_s3_credentials
    response.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://api.maap-project.org/api/members/self/awsAccess/edcCredentials/https%253A%252F%252Fsentinel1.asf.alaska.edu%252Fs3credentials
```

**Comment by wildintellect** [comment]
@bsatoriu made some fixes to the maap-py api to enable working is ASF (Link?)

```
maap.getJobStatus("6174249a-ceb5-4712-b913-70ec4660f20e")
'Succeeded'
```

I can confirm a valid S1A SLC zip was downloaded, checked by unzipping. Unzipping actually broke the `my-private-bucket` mount in my workspace part way through the unzip. But that is a different issue.

cc: @nemo794 @omshinde
